name: 刷课
 
on: 
  push:
    branches: [ main ]
 
jobs: 
  Start:
    runs-on: ubuntu-latest # 在最新版本的 Ubuntu 操作系统环境下运行
    steps: # 要执行的步骤
      - name: 拷贝代码
        uses: actions/checkout@v3  # 用于将github代码仓库的代码拷贝到工作目录中
 
      - name: 设置python环境
        uses: actions/setup-python@v2 # 用于设置 Python 环境，它允许你指定要在工作环境中使用的 Python 版本
        with:
          python-version: '3.9'  # 选择要用的Python版本
 
      - name: 安装依赖包
        run: | # 安装依赖包
          pip install -r ./requirements.txt 
          
      
      - name: Run main.py
        run: python main.py -u 学习通账号 -p 学习通密码 -l 244403509 #课程id，默认为心理课的
